// This file was generated by Slater.app - OZO Verbindzorg

let paths = window.location.pathname.split('/')


// Examples slider -> 
import('https://slater.app/9398/20514.js?v=243217')


// Form label -> 
import('https://slater.app/9398/20492.js?v=644910')


// Lenis -> 
import('https://slater.app/9398/21057.js?v=710523')


// Logo's -> 
import('https://slater.app/9398/20491.js?v=863754')


// Play Video -> 
import('https://slater.app/9398/20486.js?v=930025')


// Reviews -> 
import('https://slater.app/9398/20493.js?v=550717')


// Header video -> 
{ 
   const pages = [""]; 
   const path = paths[paths.length - 1] 
   const itemPath = paths[paths.length - 2] 
   if (pages.includes(path) || pages.includes('detail_' + itemPath) || pages.includes(itemPath + '/item')) import('https://slater.app/9398/46775.js?v=304868'); 
} 
 

// Team slider -> 
{ 
   const pages = ["over-ons"]; 
   const path = paths[paths.length - 1] 
   const itemPath = paths[paths.length - 2] 
   if (pages.includes(path) || pages.includes('detail_' + itemPath) || pages.includes(itemPath + '/item')) import('https://slater.app/9398/21432.js?v=925970'); 
} 
 

// TESTCODE -> 
{ 
   const pages = ["testpage"]; 
   const path = paths[paths.length - 1] 
   const itemPath = paths[paths.length - 2] 
   if (pages.includes(path) || pages.includes('detail_' + itemPath) || pages.includes(itemPath + '/item')) import('https://slater.app/9398/64252.js?v=930108'); 
} 
 

// Vacatures slider -> 
{ 
   const pages = ["detail_werken-bij"]; 
   const path = paths[paths.length - 1] 
   const itemPath = paths[paths.length - 2] 
   if (pages.includes(path) || pages.includes('detail_' + itemPath) || pages.includes(itemPath + '/item')) import('https://slater.app/9398/22093.js?v=785405'); 
} 
 

