// This file was generated by Slater.app - Reviews.js


//Reviews slider
const swiper = new Swiper('#reviews', {
  slidesPerView: 3,
  speed: 400,
  spaceBetween: 28,

  keyboard: {
    enabled: false,
  },

  breakpoints: {
    320: {
      slidesPerView: 1.1,
      spacebetween: 16,
      centeredSlides: false,
    },
    992: {
      allowTouchMove: false,
    }
  }
});

const videos = document.querySelectorAll('video');
const playButtons = document.querySelectorAll('[id^="play-"]');
const pauseButtons = document.querySelectorAll('[id^="pause-"]');

// Pause, mute, and reset all videos
function pauseAllVideos() {
  videos.forEach(video => {
    video.pause();
    video.currentTime = 0; // Reset to start
    video.muted = true;

    // Find the corresponding pause button and simulate click
    const pauseButton = document.getElementById(`pause-${video.id}`);
    if (pauseButton) {
      pauseButton.click();
    }
  });
}

// Run on page load
pauseAllVideos();

// Play button handler
playButtons.forEach(button => {
  button.addEventListener('click', () => {
    const targetId = button.id.replace('play-', '');
    const targetVideo = document.getElementById(targetId);

    pauseAllVideos();
    targetVideo.muted = false;
    targetVideo.play();
  });
});

// Pause button handler
pauseButtons.forEach(button => {
  button.addEventListener('click', () => {
    const targetId = button.id.replace('pause-', '');
    const targetVideo = document.getElementById(targetId);

    targetVideo.pause();
    targetVideo.currentTime = 0;
    targetVideo.muted = true;
  });
});


