// This file was generated by Slater.app - Vacatures slider.js


//Vacatures slider
const swiper = new Swiper('#vacatures', {
  slidesPerView: 'auto',
  speed: 400,
  spaceBetween: 24,
  grabCursor: true,

  keyboard: {
    enabled: true,
  },

  navigation: {
    nextEl: ".swiper-next",
    prevEl: ".swiper-prev",
  },
});


