// This file was generated by Slater.app - Examples slider.js


//Examples slider
const swiper = new Swiper('#examples', {
  slidesPerView: 'auto',
  speed: 400,
  spaceBetween: 12,
  grabCursor: true,

  keyboard: {
    enabled: true,
  },

  navigation: {
    nextEl: ".swiper-next",
    prevEl: ".swiper-prev",
  },
});


