// This file was generated by Slater.app - Logo's.js


//Logos marquee
const swiper = new Swiper('#logos', {
  slidesPerView: 'auto',
  centeredSlides: true,
  loop: true,
  speed: 4000,
  spaceBetween: 28,
  enabled: true,
  simulateTouch: false,
  allowTouchMove: false,
  autoplay: {
    delay: 0,
    disableOnInteraction: false,
    pauseOnMouseEnter: false,
  },

  keyboard: {
    enabled: false,
  },
})


