// This file was generated by Slater.app - Play Video.js


/*
const video = document.getElementById('explainer-video');
const playButton = document.getElementById('play-video');
const pauseButton = document.getElementById('pause-video');

playButton.addEventListener('click', () => {
  video.muted = false; // Unmute the video
  video.play(); // Start playing the video
});

pauseButton.addEventListener('click', () => {
  video.muted = true; // Mute the video
  video.pause(); // Pause the video
});

// Add an event listener for the 'ended' event
video.addEventListener('ended', function () {
  // Pause the video when it ends
  video.pause();
});
*/


