// This file was generated by Slater.app - Team slider.js


//Team slider
const swiper = new Swiper('#team', {
  slidesPerView: 'auto',
  speed: 400,
  spaceBetween: 24,
  grabCursor: true,

  keyboard: {
    enabled: true,
  },

  navigation: {
    nextEl: ".swiper-next",
    prevEl: ".swiper-prev",
  },
});


